"use client";
import AppShell from "@/components/AppShell";
import {
  Activity,
  BarChart3,
  Bookmark,
  Eye,
  FolderKanban,
  MessageSquare,
  Sparkles,
  Users,
} from "lucide-react";
import { useEffect, useState } from "react";
export default function Analytics() {
  const [d, setD] = useState<any>(null),
    [founder, setFounder] = useState<any>(null),
    [error, setError] = useState("");
  useEffect(() => {
    fetch("/api/analytics").then(async (r) => {
      const x = await r.json();
      if (r.ok) {
        setD(x);
        if (x.role === "FOUNDER")
          fetch("/api/analytics/founder")
            .then((r) => (r.ok ? r.json() : null))
            .then(setFounder);
      } else setError(x.error);
    });
  }, []);
  const metrics =
    d?.role === "FOUNDER"
      ? [
          [FolderKanban, "Projects", d.projects?.length || 0],
          [Users, "Applications", d.applications?.length || 0],
          [Eye, "Project views", d.counts?.view_project || 0],
          [MessageSquare, "Messages", d.counts?.message_sent || 0],
        ]
      : [
          [Eye, "Profile views", d?.counts?.view_profile || 0],
          [Sparkles, "Connections", d?.connections || 0],
          [Bookmark, "Bookmarks", d?.bookmarks || 0],
          [Users, "Endorsements", d?.endorsements || 0],
        ];
  return (
    <AppShell>
      <div className="max-w-6xl mx-auto p-5 md:p-8">
        <p className="text-[10px] tracking-[.2em] text-cyan-300 font-bold">
          LIVE PERFORMANCE
        </p>
        <h1 className="text-3xl font-black mt-2">Analytics</h1>
        <p className="text-slate-500 mt-2">
          Real activity generated by your IBF profile and projects.
        </p>
        {error && <p className="mt-5 text-red-300">{error}</p>}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8">
          {metrics.map(([I, l, v]: any) => (
            <div
              className="bg-white border border-slate-200 rounded-2xl p-5"
              key={l}
            >
              <span className="h-10 w-10 bg-cyan-300/10 text-cyan-300 rounded-xl grid place-items-center">
                <I size={18} />
              </span>
              <p className="text-xs text-slate-500 mt-5">{l}</p>
              <p className="text-3xl font-black mt-1">{d ? v : "—"}</p>
            </div>
          ))}
        </div>
        {founder && (
          <section className="mt-8">
            <h2 className="text-xl font-black">Founder Insights</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-4">
              {[
                [
                  "Time to first application",
                  founder.timeToFirstApplicationHours == null
                    ? "—"
                    : `${founder.timeToFirstApplicationHours}h`,
                ],
                ["Completion rate", `${founder.completionRate}%`],
                ["30-day applications", founder.funnel.applications],
                ["Accepted applicants", founder.funnel.accepted],
              ].map(([l, v]) => (
                <div
                  className="bg-white border border-slate-200 rounded-xl p-4"
                  key={l}
                >
                  <p className="text-xs text-slate-500">{l}</p>
                  <b className="text-2xl mt-2 block">{v}</b>
                </div>
              ))}
            </div>
            <div className="grid lg:grid-cols-[1fr_320px] gap-5 mt-5">
              <div className="bg-white border border-slate-200 rounded-2xl p-5">
                <b>30-day activity</b>
                <div className="h-56 flex items-end gap-1 mt-6">
                  {founder.daily.map((x: any) => (
                    <div
                      title={`${x.date}: ${x.applications} applications`}
                      className="flex-1 bg-cyan-300/50 hover:bg-cyan-300 min-h-1"
                      style={{
                        height: `${Math.max(2, Math.min(100, (x.applications + x.connections) * 12))}%`,
                      }}
                      key={x.date}
                    />
                  ))}
                </div>
              </div>
              <div className="bg-white border border-slate-200 rounded-2xl p-5">
                <b>Conversion funnel</b>
                {[
                  ["Views", founder.funnel.views],
                  ["Applications", founder.funnel.applications],
                  ["Accepted", founder.funnel.accepted],
                  ["Completed", founder.funnel.completed],
                ].map(([l, v], i) => (
                  <div className="mt-4" key={l}>
                    <div className="flex text-xs">
                      <span>{l}</span>
                      <b className="ml-auto">{v}</b>
                    </div>
                    <div className="h-2 bg-white/5 rounded mt-2">
                      <div
                        className="h-full bg-cyan-300 rounded"
                        style={{ width: `${Math.max(4, 100 - i * 24)}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}
        <section className="mt-8 bg-white border border-slate-200 rounded-2xl p-6">
          <div className="flex">
            <div>
              <b>Recent activity</b>
              <p className="text-xs text-slate-500 mt-1">
                Events recorded for your account
              </p>
            </div>
            <Activity className="ml-auto text-cyan-300" />
          </div>
          <div className="grid sm:grid-cols-2 gap-3 mt-5">
            {d?.events?.length ? (
              d.events
                .slice(-8)
                .reverse()
                .map((e: any) => (
                  <div
                    className="p-3 border border-white/[.06] rounded-lg"
                    key={e.id}
                  >
                    <p className="text-xs font-bold">
                      {e.event_type.replaceAll("_", " ")}
                    </p>
                    <p className="text-[10px] text-slate-500 mt-1">
                      {new Date(e.created_at).toLocaleString()}
                    </p>
                  </div>
                ))
            ) : (
              <p className="text-sm text-slate-500">
                Activity will appear as you use IBF.
              </p>
            )}
          </div>
        </section>
      </div>
    </AppShell>
  );
}
