"use client";

import AppShell from "@/components/AppShell";
import {
  Activity,
  BarChart3,
  Bookmark,
  Clock,
  Eye,
  FolderKanban,
  MessageSquare,
  Sparkles,
  Target,
  TrendingUp,
  Users,
} from "lucide-react";
import { useEffect, useState } from "react";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

const DAY_MS = 86_400_000;

export default function Analytics() {
  const [d, setD] = useState<any>(null),
    [error, setError] = useState("");
  const [founder, setFounder] = useState<any>(null);
  const [founderError, setFounderError] = useState("");

  useEffect(() => {
    fetch("/api/analytics").then(async (r) => {
      const x = await r.json();
      r.ok ? setD(x) : setError(x.error);
    });
  }, []);

  const isFounder = d?.role === "FOUNDER" || d?.role === "SUPER_ADMIN";

  useEffect(() => {
    if (!isFounder) return;
    fetch("/api/analytics/founder", { cache: "no-store" })
      .then(async (r) => {
        const x = await r.json();
        r.ok ? setFounder(x) : setFounderError(x.error);
      })
      .catch(() => setFounderError("Unable to load founder insights."));
  }, [isFounder]);

  const metrics =
    d?.role === "FOUNDER"
      ? [
          [FolderKanban, "Projects", d.projects?.length || 0],
          [Users, "Applications", d.applications?.length || 0],
          [Eye, "Project views", d.counts?.view_project || 0],
          [MessageSquare, "Messages", d.counts?.message_sent || 0],
        ]
      : [
          [Eye, "Profile views", d?.counts?.view_profile || 0],
          [Sparkles, "Connections", d?.connections || 0],
          [Bookmark, "Bookmarks", d?.bookmarks || 0],
          [Users, "Endorsements", d?.endorsements || 0],
        ];

  /**
   * The seven-day chart used to be a hardcoded array of bar heights. It now
   * counts the member's own analytics events per day, and when there are none
   * the bars sit empty with an explanation instead of pretending to be data.
   */
  const last7 = Array.from({ length: 7 }, (_, index) => {
    const date = new Date(Date.now() - (6 - index) * DAY_MS);
    return {
      key: date.toISOString().slice(0, 10),
      label: date.toLocaleDateString(undefined, { weekday: "short" }).slice(0, 1),
      count: 0,
    };
  });
  const dayIndex = new Map(last7.map((day) => [day.key, day]));
  for (const event of d?.events ?? []) {
    const bucket = dayIndex.get(new Date(event.created_at).toISOString().slice(0, 10));
    if (bucket) bucket.count += 1;
  }
  const maxCount = Math.max(1, ...last7.map((day) => day.count));
  const hasActivity = last7.some((day) => day.count > 0);

  const funnel = founder?.funnel;
  const funnelBase = Math.max(1, funnel?.applications || 0);
  const funnelStages = funnel
    ? [
        {
          label: "Project views",
          value: funnel.views_available ? funnel.views : null,
          hint: funnel.views_available ? undefined : "not measured yet",
        },
        { label: "Applications", value: funnel.applications },
        { label: "Accepted", value: funnel.accepted },
        { label: "Completed projects", value: funnel.completed },
      ]
    : [];

  return (
    <AppShell>
      <div className="max-w-6xl mx-auto p-5 md:p-8">
        <p className="text-[10px] tracking-[.2em] text-cyan-300 font-bold">
          LIVE PERFORMANCE
        </p>
        <h1 className="text-3xl font-black mt-2">Analytics</h1>
        <p className="text-slate-500 mt-2">
          Real activity generated by your IBF profile and projects.
        </p>
        {error && <p className="mt-5 text-red-300">{error}</p>}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8">
          {metrics.map(([I, l, v]: any) => (
            <div className="bg-white border border-slate-200 rounded-2xl p-5">
              <span className="h-10 w-10 rounded-xl bg-cyan-300/10 text-cyan-300 grid place-items-center">
                <I size={18} />
              </span>
              <p className="text-xs text-slate-500 mt-5">{l}</p>
              <p className="text-3xl font-black mt-1">{d ? v : "—"}</p>
            </div>
          ))}
        </div>
        <div className="grid lg:grid-cols-[1fr_320px] gap-5 mt-6">
          <section className="bg-white border border-slate-200 rounded-2xl p-6">
            <div className="flex">
              <div>
                <b>Activity over time</b>
                <p className="text-xs text-slate-500 mt-1">
                  Your recorded events during the last seven days
                </p>
              </div>
              <BarChart3 className="ml-auto text-cyan-300" />
            </div>
            <div className="h-64 flex items-end gap-3 mt-8">
              {last7.map((day, index) => (
                <div className="flex-1 h-full flex flex-col justify-end" key={day.key}>
                  <div
                    className="bg-gradient-to-t from-cyan-300/30 to-cyan-300 rounded-t-md transition hover:brightness-125"
                    style={{
                      height: hasActivity
                        ? `${Math.max(8, (day.count / maxCount) * 100)}%`
                        : "4px",
                    }}
                    title={`${day.count} event${day.count === 1 ? "" : "s"}`}
                  />
                  <span className="text-[9px] text-slate-600 text-center mt-2">
                    {day.label}
                  </span>
                </div>
              ))}
            </div>
            {!hasActivity && (
              <p className="text-xs text-slate-500 mt-6">
                No events recorded yet. Counts appear here as your activity is
                tracked.
              </p>
            )}
          </section>
          <aside className="bg-white border border-slate-200 rounded-2xl p-6">
            <b>Recent events</b>
            <div className="mt-5 space-y-4">
              {d?.events?.length ? (
                d.events
                  .slice(-6)
                  .reverse()
                  .map((e: any) => (
                    <div className="flex gap-3" key={`${e.event_type}-${e.created_at}`}>
                      <span className="h-8 w-8 bg-cyan-300/10 text-cyan-300 rounded-lg grid place-items-center">
                        <Activity size={14} />
                      </span>
                      <div>
                        <p className="text-xs font-bold">
                          {e.event_type.replaceAll("_", " ")}
                        </p>
                        <p className="text-[10px] text-slate-500 mt-1">
                          {new Date(e.created_at).toLocaleString()}
                        </p>
                      </div>
                    </div>
                  ))
              ) : (
                <p className="text-sm text-slate-500">
                  Activity will appear as you use IBF.
                </p>
              )}
            </div>
          </aside>
        </div>

        {isFounder && (
          <section className="mt-10">
            <p className="text-[10px] tracking-[.2em] text-cyan-300 font-bold">
              FOUNDER INSIGHTS
            </p>
            <h2 className="text-2xl font-black mt-2">How your projects are moving</h2>

            {founderError && <p className="mt-5 text-sm text-rose-300">{founderError}</p>}

            {founder && (
              <>
                <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6">
                  {[
                    [
                      Users,
                      "Applications · 30d",
                      founder.last_30_days.applications,
                      "across all your projects",
                    ],
                    [
                      Clock,
                      "Time to first application",
                      founder.avg_days_to_first_application === null
                        ? "—"
                        : `${founder.avg_days_to_first_application}d`,
                      founder.avg_days_to_first_application === null
                        ? "no applications yet"
                        : "average per project",
                    ],
                    [
                      Target,
                      "Completion rate",
                      `${founder.completion_rate}%`,
                      `${founder.projects_by_status.COMPLETED ?? 0} of ${founder.totals.projects} completed`,
                    ],
                    [
                      Sparkles,
                      "Connections · 30d",
                      founder.last_30_days.connections,
                      `${founder.last_30_days.messages} messages sent`,
                    ],
                  ].map(([I, label, value, hint]: any) => (
                    <div className="bg-white border border-slate-200 rounded-2xl p-5" key={label}>
                      <span className="h-10 w-10 rounded-xl bg-cyan-300/10 text-cyan-300 grid place-items-center">
                        <I size={18} />
                      </span>
                      <p className="text-xs text-slate-500 mt-5">{label}</p>
                      <p className="text-3xl font-black mt-1">{value}</p>
                      <p className="text-[11px] text-slate-500 mt-1">{hint}</p>
                    </div>
                  ))}
                </div>

                <div className="grid lg:grid-cols-[1fr_360px] gap-5 mt-6">
                  <div className="bg-white border border-slate-200 rounded-2xl p-6">
                    <div className="flex">
                      <div>
                        <b>Applications received</b>
                        <p className="text-xs text-slate-500 mt-1">Last 30 days, per day</p>
                      </div>
                      <TrendingUp className="ml-auto text-cyan-300" />
                    </div>
                    <div className="h-64 mt-6">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={founder.series}>
                          <CartesianGrid stroke="rgba(148,163,184,.15)" vertical={false} />
                          <XAxis
                            dataKey="day"
                            tick={{ fill: "#8290a4", fontSize: 10 }}
                            tickFormatter={(value: string) => value.slice(5)}
                            interval={Math.floor(founder.series.length / 6)}
                            axisLine={false}
                            tickLine={false}
                          />
                          <YAxis
                            allowDecimals={false}
                            tick={{ fill: "#8290a4", fontSize: 10 }}
                            axisLine={false}
                            tickLine={false}
                            width={28}
                          />
                          <Tooltip
                            contentStyle={{
                              background: "#111827",
                              border: "1px solid rgba(148,163,184,.2)",
                              borderRadius: 12,
                              fontSize: 12,
                            }}
                            labelStyle={{ color: "#8290a4" }}
                          />
                          <Line
                            type="monotone"
                            dataKey="applications"
                            stroke="#00f5d4"
                            strokeWidth={2}
                            dot={false}
                          />
                        </LineChart>
                      </ResponsiveContainer>
                    </div>
                    {founder.last_30_days.applications === 0 && (
                      <p className="text-xs text-slate-500 mt-2">
                        No applications in the last 30 days.
                      </p>
                    )}
                  </div>

                  <div className="bg-white border border-slate-200 rounded-2xl p-6">
                    <b>Funnel</b>
                    <p className="text-xs text-slate-500 mt-1">
                      Views → applications → accepted → completed
                    </p>
                    <div className="mt-6 space-y-4">
                      {funnelStages.map((stage) => (
                        <div key={stage.label}>
                          <div className="flex text-xs">
                            <span className="text-slate-400">{stage.label}</span>
                            <span className="ml-auto font-bold">
                              {stage.value === null ? "—" : stage.value}
                            </span>
                          </div>
                          <div className="h-2 bg-white/5 rounded-full mt-2 overflow-hidden">
                            <div
                              className="h-full bg-cyan-300 rounded-full"
                              style={{
                                width:
                                  stage.value === null
                                    ? "0%"
                                    : `${Math.max(
                                        stage.value > 0 ? 6 : 0,
                                        (stage.value / funnelBase) * 100,
                                      )}%`,
                              }}
                            />
                          </div>
                          {stage.hint && (
                            <p className="text-[10px] text-slate-500 mt-1">{stage.hint}</p>
                          )}
                        </div>
                      ))}
                    </div>
                    <p className="text-[10px] text-slate-500 mt-5">
                      Project views are not instrumented yet, so that stage stays
                      blank rather than showing an invented number.
                    </p>
                  </div>
                </div>

                {founder.projects.length > 0 && (
                  <div className="overflow-x-auto mt-6">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-left text-[10px] tracking-widest text-slate-500">
                          <th className="py-3 pr-4">PROJECT</th>
                          <th className="py-3 pr-4">STATUS</th>
                          <th className="py-3 pr-4">APPLICATIONS</th>
                          <th className="py-3">FIRST APPLICATION</th>
                        </tr>
                      </thead>
                      <tbody>
                        {founder.projects.map((project: any) => (
                          <tr key={project.id} className="border-t border-slate-200">
                            <td className="py-3 pr-4 font-bold">{project.title}</td>
                            <td className="py-3 pr-4 text-slate-400">{project.status}</td>
                            <td className="py-3 pr-4 text-slate-400">{project.applications}</td>
                            <td className="py-3 text-slate-400">
                              {project.days_to_first_application === null
                                ? "—"
                                : `${project.days_to_first_application} days`}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </>
            )}
          </section>
        )}
      </div>
    </AppShell>
  );
}
