"use client";
import Link from "next/link";
import {Sparkles,Loader2} from "lucide-react";
import {FormEvent,useState} from "react";
export default function LegacySignIn(){
 const [loading,setLoading]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch('/api/auth/signin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:String(f.get('email')).trim(),password:String(f.get('password'))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to sign in');window.location.assign('/dashboard')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <div className="min-h-screen bg-[#0a0f1e] p-6 flex flex-col"><Link href="/" className="flex gap-2 items-center font-black text-xl"><span className="w-9 h-9 rounded-lg bg-cyan-300 text-slate-950 grid place-items-center"><Sparkles size={18}/></span>IBF</Link><main className="w-full max-w-md m-auto"><div className="p-4 mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] text-sm text-amber-200"><b>Legacy sign-in.</b> Existing Supabase accounts can sign in here during migration. New accounts should use <Link className="text-cyan-300 font-bold" href="/auth/signin">Clerk sign-in</Link>.</div><form onSubmit={submit} className="bg-white border border-slate-200 rounded-2xl p-6"><h1 className="text-2xl font-black">Legacy account</h1><label className="block text-sm font-bold mt-6">Email<input name="email" required type="email" autoComplete="email" className="field mt-2"/></label><label className="block text-sm font-bold mt-4">Password<input name="password" required minLength={8} type="password" autoComplete="current-password" className="field mt-2"/></label>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<button disabled={loading} className="btn btn-primary w-full mt-6">{loading&&<Loader2 size={16} className="animate-spin"/>}Sign in</button></form></main></div>
}
